W6D5/Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show]
end

W6D5/Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    validates :color, inclusion: { in: %w(black white orange), 
            message: "%{color} is not a valid color" }
    validates :sex, inclusion: { in: ["F", "M"],
            message: "choose sex from 'M' or 'F'"}

    def age(birth_date)
        @age = ((DateTime.now - birth_date) / 365.25)#.floor
    end
end

W6D5/Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        @age = @cat.age(@cat.birth_date)
        render :show
    end
end

W6D5/Cats/app/views/cats/index.html.erb
<h1>All cats</h1>

<ul>
    <% @cats.each do |cat| %>
        <li>
        <a href=" <%= cat_url %> ">
            <%= cat.name %>
        </a>
        </li>
    <% end %>


</ul>

W6D5/Cats/app/views/cats/show.html.erb
<h1>Show Cat</h1>
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>birth_date</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>description</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

W6D5/Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>